### ISSUE TITLE
index.html

### ISSUE THREAD

**Issue by priyaK9157** [0xsahilantil/DOT-Batch#1]
Please add <a> tag add in index.html file. @0xsahilantil

**Comment by 0xsahilantil** [comment]
Done

**Comment by Manoharvuradi** [comment]
@priyaK9157 can you elaborate little bit more!?

**Comment by priyaK9157** [comment]
@Manoharvuradi Nothing ..there was some problem in the code. It has been now resolved

**Comment by Manoharvuradi** [comment]
Okay
